task_manager/accounts/urls.py
from django.urls import path
from django.contrib.auth import views
from .views import UserLoginForm, signup

urlpatterns = [
    path(
        'login/',
        views.LoginView.as_view(
            template_name="registration/login.html",
            authentication_form=UserLoginForm
            ),
        name='login'
    ),
    path("register/", signup, name="register"),
]

task_manager/task_app/urls.py
from django.urls import path, include
from . import views
from task_app.views import TaskCreateView,  task_detail, delete_comment, complete_task

app_name = "task_app"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("completed", views.IndexViewCompleted.as_view(), name="index_completed"),
    # list view
    path("<int:pk>", task_detail, name="detail"),
    # detail view
    path("users/<int:pk>", views.UserDetailView.as_view(), name="user_detail"),
    path("<int:pk>/update", views.UpdateView.as_view(), name="update"),
    path("create", TaskCreateView.as_view(), name="create"),
    path("<int:pk>/delete", views.DeleteView.as_view(), name="delete"),
    path("<int:pk>/complete", complete_task, name="complete"),
    # path("users/<int:pk>/update", user_update, name="user_update"),
    path("users/<int:pk>/update", views.UserUpdateView.as_view(), name="user_update"),
    # https://stackoverflow.com/questions/68592568/how-to-delete-model-data-on-button-click-django
    # need to add a route for deleting comments from the detail page
    path("<int:pk>/delete_comment/<int:comment_id>", delete_comment, name="delete_comment")
]

task_manager/task_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect

urlpatterns = [
    path('', lambda request: redirect('tasks/', permanent=False)), #https://stackoverflow.com/questions/15706489/redirect-to-named-url-pattern-directly-from-urls-py-in-django
    path('tasks/', include('task_app.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include("accounts.urls")),
    path("accounts/", include('django.contrib.auth.urls')),
]

task_manager/task_app/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.db.models.functions import ExtractDay

class Task(models.Model):
    def __str__(self):
        return self.name
    name = models.CharField("Task name", max_length=200, default="placeholder")
    description = models.CharField("Task description", max_length=1500)
    due_date = models.DateTimeField("Due date")
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    is_completed = models.BooleanField("Is completed")
    def is_overdue(self):
        return self.due_date <= timezone.now()
    def hours_left(self):
        delta = self.due_date - timezone.now()
        days, seconds = delta.days, delta.seconds
        hours = days * 24 + seconds // 3600
        return abs(hours)

class Comment(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE, related_name='comments')
    text = models.CharField("Comment text", max_length=500, default="placeholder")
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

task_manager/task_app/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Comment

class UserUpdateForm(forms.ModelForm):
    first_name = forms.CharField(max_length=200, required=True)
    last_name = forms.CharField(max_length=200, required=True)
    email = forms.EmailField(max_length=200, help_text='Required.')
    class Meta:
        model = User
        help_texts = {
            'first_name': 'Required.',
            'last_name': 'Required.'
        }
        fields = ['username', 'first_name', 'last_name', 'email']
        
class CommentPostingForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        

task_manager/task_app/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse, reverse_lazy
from django.views import generic
from django import forms
from .models import Task, User, Comment
from django.core.exceptions import ValidationError
from django.contrib.auth.decorators import login_required
from .forms import UserUpdateForm, CommentPostingForm

class IndexView(LoginRequiredMixin, generic.ListView):
    login_url = "login"
    redirect_field_name = login_url
    template_name = "task_app/index.html"
    context_object_name = "task_list"
    
    def get_queryset(self) -> QuerySet[Any]:
        return Task.objects.order_by("due_date").filter(is_completed=False)

class IndexViewCompleted(LoginRequiredMixin, generic.ListView):
    login_url = "login"
    redirect_field_name = login_url
    template_name = "task_app/index_completed.html"
    context_object_name = "task_list"
    
    def get_queryset(self) -> QuerySet[Any]:
        return Task.objects.order_by("due_date").filter(is_completed=True)

def task_detail(request, pk):
    task = Task.objects.get(pk=pk)
    comments = task.comments.all()

    if request.method == 'POST':
        form = CommentPostingForm(request.POST)
        if form.is_valid():
            creating_comment = form.save(commit=False)
            creating_comment.created_by = request.user
            creating_comment.task = task
            creating_comment.save()
            return redirect('task_app:detail', pk=task.pk)
    else:
        form = CommentPostingForm()

    context = {
        'task': task,
        'comments': comments,
        'form': form
    }
    return render(request, 'task_app/detail.html', context)

def delete_comment(request, pk, comment_id=None):
    task = Task.objects.get(pk=pk)
    comment = get_object_or_404(Comment, pk=comment_id)
    comment.delete()
    return redirect('task_app:detail', pk = task.pk)

def complete_task(request, pk):
    task = Task.objects.get(pk=pk)
    task.is_completed = True
    task.save()
    return redirect('task_app:detail', pk = task.pk)

class TaskDetailView(generic.DetailView):
    model = Task
    template_name = "task_app/detail.html"
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['comment_form'] = CommentPostingForm()
        return context 
    
class UserDetailView(generic.DetailView):
    model = User
    template_name = "task_app/user_detail.html"
    
class UpdateView(LoginRequiredMixin, UserPassesTestMixin, generic.UpdateView):
    def test_func(self):
        obj = self.get_object()
        return self.request.user == obj
    def handle_no_permission(self) -> HttpResponseRedirect:
        obj = self.get_object()
        return redirect('task_app:detail', pk=obj.id)
    login_url = "login"
    redirect_field_name = login_url
    model = Task
    fields = ["name", "description", "due_date", "is_completed"]
    template_name = "task_app/update.html"
    success_url = reverse_lazy("task_app:index")
    
    def get_form(self):
        form = super(UpdateView, self).get_form()
        form.fields['due_date'].widget = forms.TextInput(attrs={'type':'datetime-local'})
        form.fields['name'].widget.attrs['class'] = 'form-control'
        return form
    
    def form_valid(self, form):
        if form.instance.created_by != self.request.user:
            raise ValidationError("You cannot edit a task that is not yours")
        else:
            return super().form_valid(form)
            
class UserUpdateView(LoginRequiredMixin, UserPassesTestMixin, generic.UpdateView):
    def test_func(self):
        obj = self.get_object()
        return self.request.user == obj
    def handle_no_permission(self) -> HttpResponseRedirect:
        obj = self.get_object()
        return redirect('task_app:user_detail', pk=obj.id)
    login_url = "login"
    redirect_field_name = login_url
    
    model = User
    fields = ["username", "first_name", "last_name", "email"]
    template_name = "task_app/user_update.html"
    success_url = reverse_lazy("task_app:user_detail")
    
    def form_valid(self, form):
        if form.instance.created_by != self.request.user:
            raise ValidationError("You cannot edit a user that is not yourself")
        else:
            return super().form_valid(form)
        
# def user_update(request, pk):
#     def get_context_data(self, **kwargs) -> dict[str, Any]:
#         context = super(user_update, self).get_context_data(**kwargs)
#         context['form'] = self.form_class(instance=self.request.user, initial={'email':self.request.user.email})
#         return context
    
#     if request.method == 'POST':
#         form = UserUpdateForm(request.POST, initial={'username': request.user.username})
#         if form.is_valid():
#             user = form.save()
#             return redirect('task_app:user_detail')
#     else:
#         form = UserUpdateForm()
#     return render(request, 'task_app/user_update.html', {'form': form})


class TaskCreateView(LoginRequiredMixin, generic.CreateView):
    login_url = "login"
    redirect_field_name = login_url
    success_url = reverse_lazy("task_app:index")
    model = Task
    fields = ["name", "description", "due_date", "is_completed"]
    template_name = "task_app/create.html"
    
    def get_form(self):
        form = super(TaskCreateView, self).get_form()
        form.fields['description'].widget = forms.Textarea(attrs={"rows":"5", "class":"form-control"})
        for visible in form.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'
        form.fields['due_date'].widget = forms.TextInput(attrs={'type':'datetime-local'})
        form.fields['is_completed'].widget.attrs['class'] = 'form-check-input'
        return form
    
    def form_valid(self, form):
        form.instance.created_by = self.request.user
        ##### WE NEED TO HANDLE IF A USER IS NOT LOGGED IN HERE
        return super().form_valid(form)
    
class DeleteView(LoginRequiredMixin, generic.DeleteView):
    login_url = "login"
    redirect_field_name = login_url
    model = Task
    success_url = reverse_lazy("task_app:index")
    template_name = "task_app/delete.html"

task_manager/task_app/templates/task_app/create.html
{% extends "task_app/master.html" %}

{% block title %} Create page {% endblock %}

{% block headline %} New page form {% endblock %}

{% block content %}
<form method="post">{% csrf_token %}
{% for field in form %}
    <div class="form-group my-3">
        {{ field.errors }}
        {{ field.label_tag }} {{field}}
        {% if field.help_text %}
        <p class="help">{{field.help_text|safe}} </p>
        {% endif %}
    </div>
{% endfor %}
    <input class="btn btn-primary" type="submit" value="Save">
</form>
<a class="btn btn-primary my-3" role="button" href="{% url "task_app:index" %}">To index</a>
{% endblock %}

task_manager/task_app/templates/task_app/delete.html
{% extends "task_app/master.html" %}

{% block title %}
    Confirm delete?
{% endblock %}

{% block headline %}
    Are you sure?
{% endblock %}

{% block content %}
<form method="post">{% csrf_token %}
    <p class="d-inline-block bg-primary text-white border border-primary rounded p-3 w-auto">Are you sure you want to delete "{{ object }}"?</p>
    {{ form }}
    <br>
    <a class="btn btn-primary mr-3" role="button" href="{% url "task_app:detail" object.id %}">Return<a>
    <input class="btn btn-primary m-3" role="button" type="submit" value="Delete">

</form>


{% endblock %}

task_manager/task_app/templates/task_app/detail.html
{% extends "task_app/master.html" %}
{% load crispy_forms_tags %}
{% load svg %}
{% block headline %}
    Task details
{% endblock %}

{% block content %}
<div class="taskinfo container-fluid">
    <div class="row">
        <div class="col-md-1">
            <p class=""><strong>Title:</strong></p>
        </div>
        <div class="col">
            {{ task.name }}
        </div>
    </div>
    <div class="row">
        <div class="col-md-1">
            <p><strong>Description:</strong></p>
        </div>
        <div class="col">
            {{ task.description }}
        </div>
    </div>
    <div class="row">
        <div class="col-md-1">
            <p><strong>Due on:</strong></p>
        </div>
        <div class="col">
            {{ task.due_date }}
        </div>
    </div>
    <div class="row">
        <div class="col-md-1">
            <p><strong>Created by:</strong></p>
        </div>
        <div class="col">
            {{ task.created_by }}
        </div>
    </div>
    <div class="row">
        <div class="col-md-1">
            <p><strong>Completed?:</strong></p>
        </div>
        <div class="col-md-auto">
            {% if task.is_completed %}✅{% else %}❌{% endif %}
        </div>
    </div>
</div>
<div>
    {% if task.created_by.id == user.id %}
    <a class="btn btn-primary" role="button" href="{% url "task_app:delete" task.id %}"> {% svg "trash-fill" %} Delete this task</a>
    {% endif %}
    {% if task.created_by.id == user.id %}
    <a class="btn btn-primary" role="button" href="{% url "task_app:update" task.id %}"> {% svg 'pencil-fill' %} Update this task</a>
    {% endif %}
    {% if task.is_completed is False %}
    <a class="btn btn-primary" role="button" href="{% url "task_app:complete" task.id %}"> {% svg "check-lg" %} Complete this task</a>
    {% endif %}
</div>

<h4 class="my-3"> Comments </h4>
<div class="comments border border-primary rounded">
{% for comment in task.comments.all %} 
<div class="comment p-3 m-3 border rounded border-secondary d-flex flex-column">
    <div class="comment_header d-flex justify-content-between"><span> <strong> {{comment.created_by}} on {{comment.created}} </strong> </span>{% if comment.created_by.id == user.id %} <a class="link-primary" href="{{ task.id }}/delete_comment/{{ comment.id }}"> {% svg 'trash' %} </a>{% endif %}</div>
    <div class="comment_content"><p>{{ comment.text }}</p></div>
</div>
{% endfor %}
</div>
<div class="commentform my-3">
<h4> Add a new comment </h4>
<form method="post">{% csrf_token %}
    {{ form|crispy }}
    {{ form.error_text }}
    <input class="btn btn-primary" type="submit" value="Post comment">
</form>
</div>
{% endblock %}

task_manager/task_app/templates/task_app/index.html
{% extends "task_app/master.html" %}

{% block title %}
    All tasks list
{% endblock %}

{% block headline %}
    Tasks to complete
{% endblock %}

{% block content %}

{% if task_list %}
<div class="table-responsive">
<table class="table table-hover">
    <tr>
        <th>Task name</th>
        <th>Created by</th>
        <th>Due on:</th>
        <th>Overdue?</th>
    </tr>
    {% for task in task_list %}
    <tr class="{% if task.is_overdue %}table-warning{% endif %}">
        <td><a class="link-primary" href="{% url 'task_app:detail'  task.id %}"><strong>{{ task.name }}</strong></a></td>
        <td> <a class="link-primary" href="{% url 'task_app:user_detail'  task.created_by.id %}"> {{task.created_by}}</a></td> 
        <td>{{task.due_date}}</td>
        <td class=""><strong>{% if task.is_overdue %}{{ task.hours_left }} hours overdue!{% else %}{{ task.hours_left }} hours left</strong></td>{% endif %}
    </tr>
    {% endfor %}
</table>
</div>

{% else %}
    <p>No tasks have been created.</p>
{% endif %}

{% endblock %}

task_manager/task_app/templates/task_app/index_completed.html
{% extends "task_app/master.html" %}

{% block title %}
    All tasks list
{% endblock %}

{% block headline %}
    Completed tasks
{% endblock %}

{% block content %}

{% if task_list %}

<table class="table table-hover">
    <tr>
        <th>Task name</th>
        <th>Created by</th>
    </tr>
    {% for task in task_list %}
    <tr class="{% if task.is_overdue %}table-warning{% endif %}">
        <td><a class="link-primary" href="{% url 'task_app:detail'  task.id %}"><strong>{{ task.name }}</strong></a></td>
        <a class="link-primary" href="{% url 'task_app:detail'  task.id %}"> <td>{{task.created_by}}</td> </a>
    </tr>
    {% endfor %}
</table>


{% else %}
    <p>No tasks have been created.</p>
{% endif %}

{% endblock %}

task_manager/task_app/templates/task_app/master.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{%endblock%}</title>
    {% load bootstrap5 %}
    {% load svg %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% load crispy_forms_tags %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<div class="headers d-flex flex-column">
    <h1 class="display-2 align-self-center">task.ly</h1>
</div>
<div class="topbar d-flex bd-highlight mb-3 justify-content-between">
    <div class="left">
        <a class="btn btn-primary p-2 mr-3" role="button" href="{% url "task_app:index" %}"><strong>{% svg 'house' %} Home</strong></a>
        <a class="btn btn-primary ml-auto p-2 mx-3" role="button" href="{% url "task_app:create" %}">{% svg 'file-text' %} Create a <strong>new page</strong></a>
        <a class="btn btn-primary ml-auto p-2" role="button" href="{% url "task_app:index_completed" %}">{% svg 'check-circle-fill' %} Show <strong>completed tasks</strong></a>
    </div>
    <div>
        <a class="btn btn-primary p-2 mx-3" role="button" href="{% url "task_app:user_detail" user.id %}">{% svg 'person-fill' %} Currently logged in as: <strong> {{ request.user }} </strong> </a>
        <a class="btn btn-primary p-2 ml-3" role="button" href="{% url "logout" %}">{% svg 'person-fill-x' %} <strong>Logout</strong></a> 
    </div>
</div>
<h2 class="display-5 my-3">{% block headline %}{% endblock %}</h2>
<body class="p-4">
    {% block content %}
    {% endblock %}
</body>
</html>

task_manager/task_app/templates/task_app/update.html
{% extends "task_app/master.html" %}
{% load crispy_forms_tags %}
{% block title %} Updating task {% endblock %}

{% block headline %} Update task {% endblock %}

{% block content %}
<form method="post">{% csrf_token %}
{% comment %} {% for field in form %}
    <div class="form-group my-3">
        {{ field.errors }}
        {{ field.label_tag }} {{field}}
        {% if field.help_text %}
        <p class="help">{{field.help_text|safe}} </p>
        {% endif %}
    </div>
{% endfor %} {% endcomment %}
{{ form|crispy }}
    <input class="btn btn-primary" type="submit" value="Update task">
</form>
{% endblock %}

task_manager/task_app/templates/task_app/user_detail.html
{% extends "task_app/master.html" %}

{% block headline %}
    User information
{% endblock %}

{% block content %}
<div class="border border-primary rounded p-3">
    <h3>{{ user.first_name|title }} {{ user.last_name|title }}</h3>    
    <h6>Username: <strong> {{ user }} </strong> </h6>
    <h6>You can contact me via email at:<strong> {{ user.email }} </strong></h6> 
</div>
    {% if user.id == request.user.id %}<a class="btn btn-primary my-3" type="button" href={% url "task_app:user_update" user.id %}>Update info</a> {% endif %}
{% endblock %}

task_manager/task_app/templates/task_app/user_update.html
{% extends "task_app/master.html" %}
{% load crispy_forms_tags %}

{% block title %}
    Updating user
{% endblock %}

{% block headline %}
    Updating user information
{% endblock %}

{% block content %}
<form>    
    {{ form|crispy }}
    <a class="btn btn-primary" type="button" href={% url "task_app:user_detail" user.id %}>Back to User info</a>
    <input class="btn btn-primary" type="submit" value="Update">
</form>    
{% endblock %}